import java.io.File;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class ReportWriter {

    public void saveReport(Report report) {
        try {

        DocumentBuilderFactory docFactory = DocumentBuilderFactory.newInstance();
        DocumentBuilder docBulider = docFactory.newDocumentBuilder();
        Document doc = docBulider.newDocument();

        Element rootElement = doc.createElement("report");
        doc.appendChild(rootElement);

        addTag(doc, rootElement, "id", String.valueOf(report.getReportId()));
        addTag(doc, rootElement, "process_id", String.valueOf(report.getProcessId()));
        addTag(doc, rootElement, "type",(report.getReportType()));
        addTag(doc, rootElement,"department", "General_Depot");
        addTag(doc, rootElement, "author_id", "0");
        addTag(doc, rootElement, "title" , report.getTitle());
        addTag(doc, rootElement, "content", "Generated by System");

        TransformerFactory transformerFactory =TransformerFactory.newInstance();
        Transformer transformer = transformerFactory.newTransformer();
        DOMSource source = new DOMSource(doc);

        String filename = "repprt_" + report.getReportId() + ".xml";
        File dest = new File(filename);
        StreamResult result = new StreamResult(dest);

        transformer.transform(source, result);

        System.out.println("SUCCESS: saved report to " + filename);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void addTag(Document doc, Element root, String tagName, String textValue){
        Element tag = doc.createElement(tagName);
        tag.appendChild(doc.createTextNode(textValue));
        root.appendChild(tag);
    }
}